server:
  servlet:
    context-path: /backend
  port: 8083

app:
  host: http://app.zeeven.com
  api-host: http://api.zeeven.com
  images-host: http://files.chillo.fr
  invitations:
    exchange: tech.invitations.exchange
    limit: 1
  messages:
    exchange: messages
    status:
        queue: messages.status
  files:
    exchange: tech.files.exchange
    virtual-host: prod-notifications
  administrator:
      email: no-reply@zeeven.eu
      firstname: Marlene
      lastname: "DE ZEEVEN"
spring:
  jackson:
    deserialization:
        read-unknown-enum-values-as-null: false
    serialization:
        write-dates-as-timestamps: false
  rabbitmq:
    virtual-host: prod-notifications
    template:
      exchange: tech.messages.exchange
  task:
    scheduling:
        pool:
            size: 10
  application:
    name: ms-zeeven
  data:
    mongodb:
      database: ${spring.application.name}
  mail:
    activation-url: ${app.host}/activer-mon-compte?code=
    password-url: ${app.host}/activer-mon-compte?code=
    new-password-url: ${app.host}/activer-mon-compte?code=

mongock:
  migration-scan-package:
    - com.cs.ge.changelog
rsa:
    private-key: classpath:certificates/private.pem
    public-key: classpath:certificates/public.pem
jwt:
  header: 'Authorization'
  secret: 'AL_KEY'
  expiration: 3600 # (secondes) == 1 heure
  route:
    authentication:
      path: '/login'
      refresh: '/refresh'
providers:
  backoffice:
    host: https://backoffice.zeeven.chillo.fr
    base-path: items
  maxmind:
    host: https://geolite.info
    base-path: geoip/v2.1/city
  iplocation:
    host: https://api.ipgeolocation.io
    base-path: ipgeo
    key: hellokey
  notifications:
    host: 192.168.1.100:27192
    base-path: api/v1
  whatsapp:
    api-endpoint: "https://wa.me"
    host: https://graph.facebook.com/v13.0/${providers.whatsapp.phone}
    phone: 108190935266755
  twilio:
    ACCOUNT_SID: ACcbb01f55e3469ff5eea683ebc1aac50f
    AUTH_TOKEN: 1778b79bac3e35612ed996f5cb2531f4
  stripe:
    key:
      secret: hellokey
      webhooksecret: hellosecret
  front:
    host: http://hellohost.com
cors:
  urls: 'http://localhost:3000,https://app.zeeven.chillo.fr'
resources:
  images:
    folder: "applications/zeeven/images"
    host: https://app.zeeven.chillo.fr
    root: /var/www
feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: full
logging:
  level:
    org.springframework.security: DEBUG
    com.cs.ge: DEBUG
org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: DEBUG
