server:
  servlet:
    context-path: /backend
  port: 8083
app:
  host: http://app.zeeven.com
  api-host: http://api.zeeven.com
  images-host: http://files.chillo.fr
  invitations:
    exchange: tech.invitations.exchange
    limit: 1
  messages:
    exchange: messages
    status:
      queue: messages.status
  files:
    exchange: tech.files.exchange
    virtual-host: prod-notifications
  administrator:
    email: no-reply@zeeven.eu
    firstname: Marlene
    lastname: "DE ZEEVEN"
spring:
  jackson:
    deserialization:
      read-unknown-enum-values-as-null: false
    serialization:
      write-dates-as-timestamps: false
  task:
    scheduling:
      pool:
        size: 10
  application:
    name: ms-zeeven
  data:
    mongodb:
      database: ${spring.application.name}
  mail:
    activation-url: ${app.host}/activer-mon-compte?code=
    password-url: ${app.host}/activer-mon-compte?code=
    new-password-url: ${app.host}/activer-mon-compte?code=

mongock:
  migration-scan-package:
    - com.cs.ge.changelog
rsa:
  private-key: classpath:certificates/private.pem
  public-key: classpath:certificates/public.pem
jwt:
  header: 'Authorization'
  secret: 'AL_KEY'
  expiration: 3600 # (secondes) == 1 heure
  route:
    authentication:
      path: '/login'
      refresh: '/refresh'
providers:
  backoffice:
    host: https://backoffice.zeeven.chillo.fr
    base-path: items
  maxmind:
    host: https://geolite.info
    base-path: geoip/v2.1/city
  iplocation:
    host: https://api.ipgeolocation.io
    base-path: ipgeo
  notifications:
    host: 192.168.1.100:27192
    base-path: api/v1
  callback:
    host: https://api.notifications.chillo.fr
    path: ${providers.callback.host}/api/hooks
  brevo:
    host: https://api.brevo.com
    path: v3/smtp/email
  whatsapp:
    api-endpoint: "https://wa.me"
    host: https://graph.facebook.com/v17.0/${providers.whatsapp.phone}
    template-host: https://graph.facebook.com/v16.0/${providers.whatsapp.waba-id}
    callback-path: ${providers.callback.path}/whatsapp
  twilio:
    alpha-id: ZEEVEN
    host: https://api.twilio.com/2010-04-01/Accounts
    callback-path: ${providers.callback.path}/twilio
  vonage:
    callback-path: ${providers.callback.path}/vonage


cors:
  urls: 'http://localhost:3000,https://app.zeeven.chillo.fr'
resources:
  images:
    folder: "applications/zeeven/images"
feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: full
logging:
  level:
    org.springframework.security: DEBUG
    com.cs.ge: DEBUG
org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: DEBUG
