app:
  host: https://api.zeeven.chillo.fr
  invitations:
    exchange: tech.invitations.exchange
spring:
  data:
    mongodb:
      host: db-zeeven
  mail:
    #host:  mails.dev
    accountLink: ${app.host}/activer-mon-compte?code=


resources:
  images:
    host: https://zeeven.fr
    root: /var/www

org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG





